### ISSUE TITLE
Surface geodes?

### ISSUE THREAD

**Issue by Baelarius** [TheDeathlyCow/more-geodes-reforged#7]
Since updating to v1.2 for Minecraft 1.20.1, I have noticed instances of geodes from this mod appearing on the surface of the world, rather than being "underground" (i.e., they are simply sitting on the ground with the top and sides fully exposed to the air. Was this intentional?

**Comment by TheDeathlyCow** [comment]
Yes this was intentional. Part of the plaacement overhaul involved moving emerald geodes (and to a smaller extent lapis geodes) to only generate at higher elevations. This had the consequence of them sometimes appearing on the surface. But, to me this is fine, S many geodes in real life are found on the surface, not deep underground. Furthermore, in heavily modded environments, this change balanced the goal to have emerald geodes appear more in Mountains with the reality that many modded environments use mods that add tons of cave biomes, basically eliminating all underground areas that are still marked as "mountains" (and thus, making it impossible for emerald geodes to generate at all).

**Comment by Baelarius** [comment]
Awesome Possum, just wanted to make sure, as I was not expecting this.
Love the mod, btw.
